services:
  spot-ros2:
    build: .
    volumes:
      - .:/home/spot_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /home/spot_ws
    environment:
      - SPOT_NAME=${SPOT_NAME:-Spot}
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=42
      - HOME=/home/spot_ws
      - USER=root
    command: >
      bash -c "
        source /opt/ros/humble/setup.bash && 
        echo '🎉 Container pronto! Executando comandos manualmente...' &&
        exec bash
      "
    stdin_open: true
    tty: true
    network_mode: host
