# Copyright (c) 2024-2025 Boston Dynamics AI Institute LLC. All rights reserved.

/**:
  controller_manager:
    ros__parameters:
      update_rate: 333
      foot_state_broadcaster:
        type: spot_controllers/FootStateBroadcaster
      forward_position_controller:
        type: spot_controllers/ForwardStateController
      forward_state_controller:
        type: spot_controllers/ForwardStateController
      imu_sensor_broadcaster:
        type: spot_controllers/SpotIMUBroadcaster
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      spot_joint_controller:
        type: spot_controllers/SpotJointController
      spot_pose_broadcaster:
        type: spot_controllers/SpotPoseBroadcaster
      arm_controller:
        type: joint_trajectory_controller/JointTrajectoryController
      gripper_controller:
        type: joint_trajectory_controller/JointTrajectoryController
      hardware_components_initial_state:
        unconfigured:
        - SpotSystem
  forward_position_controller:
    ros__parameters:
      joints:
        - front_left_hip_x
        - front_left_hip_y
        - front_left_knee
        - front_right_hip_x
        - front_right_hip_y
        - front_right_knee
        - rear_left_hip_x
        - rear_left_hip_y
        - rear_left_knee
        - rear_right_hip_x
        - rear_right_hip_y
        - rear_right_knee
      interface_names:
        - position
  forward_state_controller:
    ros__parameters:
      joints:
        - front_left_hip_x
        - front_left_hip_y
        - front_left_knee
        - front_right_hip_x
        - front_right_hip_y
        - front_right_knee
        - rear_left_hip_x
        - rear_left_hip_y
        - rear_left_knee
        - rear_right_hip_x
        - rear_right_hip_y
        - rear_right_knee
      interface_names:
        - position
        - velocity
        - effort
  spot_joint_controller:
    ros__parameters:
      joints:
        - front_left_hip_x
        - front_left_hip_y
        - front_left_knee
        - front_right_hip_x
        - front_right_hip_y
        - front_right_knee
        - rear_left_hip_x
        - rear_left_hip_y
        - rear_left_knee
        - rear_right_hip_x
        - rear_right_hip_y
        - rear_right_knee

  arm_controller:
    ros__parameters:
      joints:
        - arm_sh0
        - arm_sh1
        - arm_el0
        - arm_el1
        - arm_wr0
        - arm_wr1
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      state_publish_rate: 50.0
      action_monitor_rate: 20.0
      allow_partial_joints_goal: false
      constraints:
        stopped_velocity_tolerance: 0.01
        goal_time: 0.6
        arm_sh0:
          trajectory: 0.1
          goal: 0.1
        arm_sh1:
          trajectory: 0.1
          goal: 0.1
        arm_el0:
          trajectory: 0.1
          goal: 0.1
        arm_el1:
          trajectory: 0.1
          goal: 0.1
        arm_wr0:
          trajectory: 0.1
          goal: 0.1
        arm_wr1:
          trajectory: 0.1
          goal: 0.1

  gripper_controller:
    ros__parameters:
      joints:
        - arm_f1x
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      state_publish_rate: 50.0
      action_monitor_rate: 20.0
      allow_partial_joints_goal: false
      constraints:
        stopped_velocity_tolerance: 0.01
        goal_time: 0.6
        arm_f1x:
          trajectory: 0.05
          goal: 0.05
