# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - arm_sh0
      - arm_sh1
      - arm_el0
      - arm_el1
      - arm_wr0
      - arm_wr1
    command_interfaces:
      - position
    state_interfaces:
      - position
    interface_name: position

gripper_controller:
  ros__parameters:
    joints:
      - arm_f1x
    command_interfaces:
      - position
    state_interfaces:
      - position
    interface_name: position